### ISSUE TITLE
MultiSpeakerBRIR released as SOFAConventionsVersion 0.1 cannot be loaded anymore

### ISSUE THREAD

**Issue by VeraE** [sofacoustics/API_MO#13]
Since commit 20dfca1 I get the error:

Error using SOFAupdateDimensions (line 107)
Data.Delay: dimension could not be matched.

Error in SOFAload (line 178)
        Obj = SOFAupdateDimensions(Obj);

Seems to be a problem with updating the dimension of Data.Delay, which in 0.1 used to be IR or MR and from 0.2 on has to be IRE or MRE.

**Comment by petibub** [comment]
Dear Vera,

seems like a backward-compatibility issue. Could you send me a link to 
that SOFA file?

Thanks,
Piotr


Vera Erbes wrote:
>
> Since commit c8494dc 
> <https://github.com/sofacoustics/API_MO/commit/c8494dc550e04bc8250c706362aa47d2666a618b> 
> I get the error:
>
> Error using SOFAupdateDimensions (line 107)
> Data.Delay: dimension could not be matched.
>
> Error in SOFAload (line 178)
> Obj = SOFAupdateDimensions(Obj);
>
> Seems to be a problem with updating the dimension of Data.Delay, which 
> in 0.1 used to be IR or MR and from 0.2 on has to be IRE or MRE.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sofacoustics/API_MO/issues/13>.
>


-- 
Piotr Majdak
Psychoakustik und Experimentelle Audiologie
Institut für Schallforschung <http://www.kfs.oeaw.ac.at>
Österreichische Akademie der Wissenschaften <http://www.oeaw.ac.at/>
Wohllebengasse 12-14, 1040 Wien
Tel.: +43 1 51581-2511
Fax: +43 1 51581-2530

**Comment by VeraE** [comment]
Hi Piotr,

you can find it here:
http://data.bbcarp.org.uk/sbsbrir/sofa/

**Comment by petibub** [comment]
Dear Vera,

there are some problems with not-backward-compatible conventions on 
loading and saving in the API.

I suggest to do the following:

x=SOFAload('SBS_BRIR_something.sofa','nochecks'); % load the file without any checks

x.Data.Delay=zeros(1,x.API.R,x.API.E); % correct the size of Data.Delay (in these files, Data.Delay is unused, so we can fill it safely with zeros)

x=SOFAupdateDimensions(x); % just a check to show that we are safe now


now x can be used, but it still will be in the old conventions version. 
When saved with SOFAsave, it will be converted to the newest version, 
The new file can be then loaded with all the checks as expected.

Hope that helps,
Piotr


Vera Erbes wrote:
>
> Hi Piotr,
>
> you can find it here:
> http://data.bbcarp.org.uk/sbsbrir/sofa/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sofacoustics/API_MO/issues/13#issuecomment-182497241>.
>


-- 
Piotr Majdak
Psychoakustik und Experimentelle Audiologie
Institut für Schallforschung <http://www.kfs.oeaw.ac.at>
Österreichische Akademie der Wissenschaften <http://www.oeaw.ac.at/>
Wohllebengasse 12-14, 1040 Wien
Tel.: +43 1 51581-2511
Fax: +43 1 51581-2530

**Comment by VeraE** [comment]
Dear Piotr,

thanks, that worked, though it would have been nicer if it could be solved automatically. I wasn't aware of the 'nochecks' option, though.

Kind regards,
Vera
