### ISSUE TITLE
Loading of SOFA file fails

### ISSUE THREAD

**Issue by jacobriiser** [sofacoustics/API_MO#21]
Hi,

I am having some issues, loading a SOFA file, that I have created myself, using python-sofa 0.2.0 [attached in a zip archive](https://github.com/sofacoustics/API_MO/files/5379446/testSofa.zip).
I can load the file in Python, but using SOFA API for Matlab and Octave 1.0.4 throws an error, when I try to do the same.
I cannot exclude the possibility that the SOFA file itself is malformed, but the nature of the error puzzles me.
When trying to read the SOFA file in Matlab (R2018b), I see that while reading the attribute "ListenerPosition", "Type' holding the value 'cartesian', the function getAtt.m throws an error because the command in line 51:
xtype = netcdflib('inqAtt',ncid,varid,attname);
returns xtype = 12, and the subsequent switch case tests for integer values in the closed range [1:11].
As a result, the function is unable to return a valid funcstr, and instead it returns an error.

The error appears to me to be somewhat similar to the errors reported in the now closed [issue 16](https://github.com/sofacoustics/API_MO/issues/16)

The attached testfile is based on another file, and comparing the properties for the Listener.Position.Type in Python shows that they are the same for the original file and for the decimate one, I have generated in Python.

Is there any simple tests/verifications that I can do to shed some more light on this issue?

Br,
Jacob Riiser

**Comment by petibub** [comment]
Dear Jacobriiser, I'll check your file ASAP (=next week) and come back to you. Regards, Piotr

**Comment by jacobriiser** [comment]
Hi Piotr,
FYI: Today, I have looked at the string termination for the attributes in the files, and it seems that in the Python generated file, attribute texts (such as 'cartesian') are Null terminated, whereas in the file that can be read by Matlab, the same attribute strings are (mostly?) terminated with 0x0C (Form Feed).
I have tried manually changing the termination from 0x00 to 0x0C, but I did not see any change in the behaviour, when trying to load the updated sofa file in Matlab.
Br Jacob

**Comment by jacobriiser** [comment]
Hi again,
It seems that I may have found a bug in the Python-Sofa code, that I have been using for writing the Sofa files.
I have added [an issue on the Python-Sofa GitHub](https://github.com/spatialaudio/python-sofa/issues/3), and I suggest to not spend time on this  before the Python-Sofa issue has been solved.
Sorry for causing disturbance here,
BR Jacob

**Comment by petibub** [comment]
Thanks!
