### ISSUE TITLE
[help] demo_FreeFieldHRTF not working for different datasets

### ISSUE THREAD

**Issue by davircarvalho** [sofacoustics/API_MO#22]
Hello, 

I'm testing HRTF interpolation using the demo_FreeFieldHRTF script, and it works fine when using the **thk** dataset. However when I try it for the **cipic** dataset by replacing the line 

`IR=SOFAload('db://database/thk/HRIR_L2354.sofa');
`
with

`IR=SOFAload('db://database/cipic/subject_003.sofa');
`

the intepolated magnitude spectra in the median plane doesn't resemble at all the reference plot. I did try using Lmax as the SH order, but no improvements - this might be a naive issue, but can you help me figure this out?

**Comment by petibub** [comment]
If by "doesn't resemble at all the reference plot" you mean that you get huge interpolation errors: CIPIC has a large gap at the bottom, thus, spatial interpolation in the SH domain yields huge errors, especially in the proximity of the gap (see Gibbs phenomenon)
