### ISSUE TITLE
[bug] SOFAconvertCIPIC2SOFA inverted channels

### ISSUE THREAD

**Issue by davircarvalho** [sofacoustics/API_MO#28]
Hello, 

I am playing around with the CIPIC dataset and noticed the results for the conversion with SOFAconvertCIPIC2SOFA.m results in HRIR for the ipsislateral ear having lower amplitude than the contralateral ear. The CIPIC HRTFs in sofaconventions.org also seem to have the same issue (assuming channel 1 is for left and 2 is for the right, as is described in all the other datasets). 

Here is an example of such observation:

![ir](https://user-images.githubusercontent.com/49624338/108373012-2e654800-71de-11eb-9925-c841d39ce868.png)

The code used to plot the image above:

```matlab
CIPIC = load([local '\hrir_final.mat']);
Obj=SOFAconvertCIPIC2SOFA(CIPIC);
idx = dsearchn(Obj.SourcePosition(:,[1,2]), [90, 0]);
ir = squeeze(Obj.Data.IR(idx,:,:));

plot(ir.')
legend('left', 'right')
title(['azim: ' num2str(Obj.SourcePosition(idx,1)),...
      '° elev: ' num2str(Obj.SourcePosition(idx,2)) '°']);
```

**Comment by isfmiho** [comment]
Dear Davi,

it seems that CIPIC and SOFA have an inverted mapping of azimuth angles 
(left / right).

I'm quite sure that a "-" in SOFAconvertCIPIC2SOFA should fix the 
problem. I will check and fix that on Monday or Tuesday.

row 34 -->
/[azi,ele]=hor2sph(*-*lat(ii),pol(ii));/

Best regards,
Michael


Am 18.02.2021 um 15:45 schrieb Davi Carvalho:
