### ISSUE TITLE
Apparent elevation calculation might be broken

### ISSUE THREAD

**Issue by hagenw** [sofacoustics/API_MO#3]
SOFAcalculateAPV calculated a wrong azimuth angle. I fixed it by disabling all the conversion to and back from horizontal-polar coordinate in order to calculate the apparent elevation.
This means the apparent elevation could be broken now and has to be checked again.

**Comment by hagenw** [comment]
As of 735c357bf30e69eb57e25803ab0a0dc321905f8c SOFAcalculateAPV() returns now again elevation and distance besides azimuth. The elevation angle should be correct, but it was not tested so far.

**Comment by petibub** [comment]
Thanks a lot! (although, I did not test it either ;.-) ).
