### ISSUE TITLE
Missing flag for mandatory fields in FreeFieldHRTF and SimpleFreeFieldHRTF

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/API_MO#37]
In the conventions `FreeFieldHRTF.csv` and `SimpleFreeFieldHRTF.csv` the line

```N:Units	hertz			attribute```

must be replaces by

```N:Units	hertz	m		attribute```

because N:Units is a mandatory parameter according to AES69-2020 Tables C.3 and C.4. Note that C.4 forgets to mention that N:LongName is optional

**Comment by isfmiho** [comment]
fixed
