### ISSUE TITLE
GeneralSOS convention missing

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/API_MO#39]
I noted that there is no `GeneralSOS` convention. It would be consistent to have it and fairly easy to generate, and it could easily be verified using sofar. Should we add it?

**Comment by petibub** [comment]
Good idea. I note that for the standard...

**Comment by f-brinkmann** [comment]
Sounds good - I'll try to find time for a draft before the next standards meeting :)

**Comment by f-brinkmann** [comment]
Nothing I have in mind. In this case I thought it would be nice to have a complete set of General* conventions. But I am also fine with leaving it as a pull until a use case emerges.

**Comment by isfmiho** [comment]
Pleas re-open this topic once data is available.

**Comment by f-brinkmann** [comment]
I have a vague memory that we said we wanted to have this for completeness in this case, without data but I'm not sure. @petibub  do you remember? I'm fine with both anyhow

**Comment by f-brinkmann** [comment]
Sorry, I did not realize that this is the issue not the pull. In the pull we agreed to include it in API_MO: https://github.com/sofacoustics/API_MO/pull/41
