### ISSUE TITLE
CIPIC files on sofaconventions.org have mirrored lateral angles

### ISSUE THREAD

**Issue by jpauwels** [sofacoustics/API_MO#42]
Hi all, the SOFA files on http://sofacoustics.org/data/database/cipic/ apparently were generated with `API_MO/converters/SOFAconvertCIPIC2SOFA.m` before https://github.com/sofacoustics/API_MO/commit/279c2e136eb69e2add7e8426949214238870594d compensated for the reversal in lateral angle direction. It would be great if corrected files could be uploaded there.

**Comment by isfmiho** [comment]
Dear [jpauwels](https://github.com/jpauwels),
they should have been fixed already two years ago, and they seem fine to me. 
When did you download the files??

![cipic](https://user-images.githubusercontent.com/12407858/165235339-15d676b9-7416-4c4c-ab9c-08c7ad09d941.jpg)

**Comment by isfmiho** [comment]
Hi @jpauwels, thank you for the feedback.
The files should be fixed now, can you please check again?

**Comment by jpauwels** [comment]
Thanks @isfmiho, it's fixed now indeed.
