### ISSUE TITLE
Load and Save .sofa files automaticly changes .sofa file ability to be recognized as a valid by steam Audio (Unity)

### ISSUE THREAD

**Issue by Vasco-Rosa** [sofacoustics/API_MO#43]
I need to create a HRIR that doesn't change the signal, but in the process of creating I ran into this problem:

When I load a .sofa file (from MIT) with SOFAload function and then save it again with SOFAsave the information that is there changes  (regardless of level of compression I choose) - I can see by the size of the new file, and because Unity (specifically Steam Audio) can't read it, while before it could. 

In attachment there is the original .sofa file from MIT and the file after being read and saved using the API (Matlab_edit sofa file). There is also a print of the code (which is pretty basic).

[issue.zip](https://github.com/sofacoustics/API_MO/files/8805951/issue.zip)

**Comment by isfmiho** [comment]
I reproduced the code that you posted. The newly created file can be loaded without any issues. Yes, the file changes depending on the version of the SOFA API you are using (some version numbers are updated). 
DateCreated and DateModified are also updated when saving a new file.

The parameter '0' causes no compression which increases the file size significantly.

You can run this commands to compare attributes:

`SOFAstart;`
`Obj=SOFAload('hrtfmitkemar.sofa');`
`SOFAsave('hrtfmitkemar2.sofa',Obj);`
`Obj2=SOFAload('hrtfmitkemar2.sofa');`
`[TF,REASON,WHERE] = **SOFAcompare**(Obj, Obj2)`
